### ISSUE TITLE
Speed of mouse movement

### ISSUE THREAD

**Issue by BASHWANE** [AntoinePassemiers/Realistic-Mouse#1]
Can you change the speed of the mouse movement?

**Comment by AntoinePassemiers** [comment]
Not currently. I'll try to add this feature this week if needed.

**Comment by joaomcarlos** [comment]
This is pretty cool but its extremely slow, like, grandma watching soap opera on tv while using pc, slow :D 

Let me leave with some ideas:

Something useful would be to allow to specify mouse speed, accuracy and on how an action should take and from that derive a realistic movement.

Speed could relate to user reaction time and/or mouse speed.
Accuracy could add to the "misses" and over corrections (momentum). 
How long an action should take would basically "string pull" actions from between start and end and get an acceptable amount of "humanness" within the time constraints available.

**Comment by AntoinePassemiers** [comment]
Hi @joaomcarlos , what OS are you using? Also what is your screen resolution?

Can you send me the code you ran, so I can try reproducing it?

**Comment by joaomcarlos** [comment]
Hi @AntoinePassemiers 

I am on Windows 11, and used the example in the readme with the mouse type of MOUSE.

I have a ultrawide screen, 5120x1440, but was only moving a small amount of distance (maybe 400px?) within a window, at about the center of the screen ... say something like 2000:100 to 2100:400.

Does that help?

**Comment by AntoinePassemiers** [comment]
I've added a speed parameter (see the README file). Movements don't look natural when you accelerate them, so I will consider improving these in future work.
